apiVersion: autoscaling/v2

## automatically adds or removes replicas based on traffic (like hiring/firing waiters)
kind: HorizontalPodAutoscaler
metadata:
  name: stock-portfolio-hpa
  labels:
    app: stock-portfolio
spec:
#which deployment to watch or to scale 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stock-portfolio-app
  # always keep at least 1 replica, never more than 3
  minReplicas: 1 
  maxReplicas: 3
  metrics:
    # if CPU goes above 70% → add more replicas
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # if memory goes above 80% → add more replicas
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      # wait 30 seconds before adding replicas (scale up fast)
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleDown:
      # wait 120 seconds before removing replicas (scale down slow)
      # reason: traffic might spike again immediately
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
